// Hashcode () :- For every object there is a unique number generated by JVM , that unique number is nothing but hashcode .

class Test
{
	public static void main (String[]args)	{
		Test t1=new Test();
		System.out.println(t1.hashcode());
		
	}
	public int hashcode()
	{
		return 10;
	}
}

